package Automation

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	CampaignApi
	ContactCampaignApi
	TriggerApi
	CampaignLogApi
	SequenceApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
